arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.gen.dart
nullable-getter: false
synthetic-package: false
untranslated-messages-file: lib/l10n/arb/missing_localizations.json
