name: flutter_dev_toys
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  lean_extensions: ^0.12.1
  url_launcher: ^6.2.2

dev_dependencies:
  custom_lint: ^0.5.7
  flutter_sane_lints: ^0.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
