name: flutter_dev_toys
description: A collection of simple dev tools inspired by Dev Toys.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.3 <4.0.0"

dependencies:
  archive: ^3.4.10
  collection: ^1.18.0
  crypto: ^3.0.3
  desktop_drop: ^0.4.4
  file_saver: ^0.2.9
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image: ^4.1.3
  image_picker: ^1.0.5
  intl: ^0.18.1
  lean_extensions: ^0.12.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.2

dev_dependencies:
  # boolean_lints: ^2.0.0
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_gen_runner: ^5.3.2
  flutter_sane_lints: ^0.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
